name: psikolog_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  linear_progress_bar: ^1.1.2
  flutter_otp_text_field: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/infrastructure/assets/Wave.jpg
    - lib/infrastructure/assets/goodbye_5821940.png
    - lib/infrastructure/assets/clap_9971688.png
    - lib/infrastructure/assets/speech-bubble_2598981.png
    - lib/infrastructure/assets/lock_4822441.png
